// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sybmielpcdvtvyuyiziy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5Ym1pZWxwY2R2dHZ5dXlpeml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTM0NTYsImV4cCI6MjA3MDEyOTQ1Nn0.TWZ2zc43NZLwHUomfzyyjyCdBAIDDAQ7-RPfLkw18Vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});